Добавлено шестнадцатое дз
leonidkit/thinknetica pull request #36
Opened 2020-12-28 22:12 UTC by leonidkit

1) Добавлены методы добавления, удаления, обновления записи в двоичном дереве.
2) Реализованы соответственные методы api.
3) Написаны тесты.

2020-12-29 10:54 UTC, DmitriyVTitov requested changes
Много ошибок, не принимаю.

2020-12-29 10:54 UTC, DmitriyVTitov commented on hw16/cmd/gosearch/main.go
> +type Gosearch struct {
лучше с маленькой

2020-12-29 10:54 UTC, DmitriyVTitov commented on hw16/pkg/api/api.go
> +	s.Router.HandleFunc("/api/update", s.Update).Methods("POST")
1. имена никуда не годятся. create что? документ? а если потребуется создавать ещё что-то?
2. имена http-методов лучше писать с помощью констант из пакета http

2020-12-29 10:54 UTC, DmitriyVTitov commented on hw16/pkg/api/api.go
> +}
функция должна возвращать что? документы или поисковый индекс?
в задании - документы, а тут - индекс.

2020-12-29 10:54 UTC, DmitriyVTitov commented on hw16/cmd/gosearch/main.go
> +}
api тоже следует сделать частью сервера

2020-12-29 10:54 UTC, DmitriyVTitov commented on hw16/pkg/api/api.go
> +		return
заменить на `http.Error()`

2020-12-29 10:54 UTC, DmitriyVTitov commented on hw16/pkg/api/api.go
> +	var req map[string]interface{}
зачем тут пустой интерфейс?
это плохой стиль программирования, не Go-way

2020-12-29 10:54 UTC, DmitriyVTitov commented on hw16/pkg/api/api.go
> +	var req map[string]interface{}
и почему вообще тут какая-то хеш-таблица? (кстати, а где используются структуры данных? вот, здесь же!)
мы же создаём документ, и получать должны документ

2020-12-29 10:54 UTC, DmitriyVTitov commented on hw16/pkg/api/api_test.go
> +}
все эти тесты по факту почти ничего не тестируют (кроме функций стандартной библиотеки)
где проверка результатов работы?

2021-01-02 11:33 UTC, DmitriyVTitov approved these changes
ОК

2021-01-02 11:33 UTC, DmitriyVTitov commented on hw16/cmd/gosearch/main.go
> +func (g *gosearch) ScanAsync(urls []string, depth int) {
желательно все неэкспортируемые функции и типы писать с маленькой

2021-01-02 11:33 UTC, DmitriyVTitov commented on hw16/cmd/gosearch/main.go
> +	data := []crawler.Document{}
странная переменная. совершенно точно лишняя.

2021-01-02 11:33 UTC, DmitriyVTitov commented on hw16/pkg/api/api.go
> +	s.Router.HandleFunc("/api/update_doc", s.Update).Methods(http.MethodPost)
такие имена - антипаттерн с точки зрения REST API. в этой концепции все ссылки должны были бы быть `/docs` с разными HTTP-методами для разных операций.
и `_` не приветствуется.
хотя я, к примеру, использую похожий RPC-стиль в именах ссылок. 

просто к сведению.

2021-01-02 11:33 UTC, DmitriyVTitov commented on hw16/pkg/api/api.go
> +		http.Error(w, "\"url\", \"title\" fields should not be empty", http.StatusBadRequest)
можно использовать \` \`

2021-01-02 11:33 UTC, DmitriyVTitov commented on hw16/pkg/api/api.go
> +	json.NewEncoder(w).Encode(s.engine.Data)
вот это не хорошо ( `Encode(s.engine.Data)` ).
оставляю вам возможность найти ошибку.

2021-01-02 11:33 UTC, DmitriyVTitov commented on hw16/pkg/api/api_test.go
> +}
тут можно проверить сколько документов вернулось

2021-01-02 11:33 UTC, DmitriyVTitov commented on hw16/pkg/api/api_test.go
> +			if !strings.Contains(string(resp), tt.Error) {
сама логика теста у вас везде одинаковая - логично было бы написать один табличный тест для всех трёх методов.

2021-01-03 01:15 UTC, leonidkit commented on hw16/pkg/api/api.go
> +	json.NewEncoder(w).Encode(s.engine.Data)
@DmitriyVTitov, не выходит понять, что не так. Думал, что, возможно, возникнет ошибка, когда Data пустая, но json маршелит просто как []. А больше идей нет...

2021-01-03 01:21 UTC, merged

2021-01-03 10:50 UTC, DmitriyVTitov commented on hw16/pkg/api/api.go
> +	json.NewEncoder(w).Encode(s.engine.Data)
HTTP-сервер - многопоточный, а s.engine.Data - общая память.
Доступ к разделяемой памяти должен быть последовательным. Обычно я делаю метод-геттер, который захватывает мьютекс и возвращает переменную.
Даже если в текущей реализации изменения по ходу работы не возможно, всё равно нужно сделать доступ последовательным.